#ifndef PARAMS_H
#define PARAMS_H

#define NTRUOAEP_N 648
#define NTRUOAEP_Q 7129

#define NTRUOAEP_SYMBYTES  32   /* size in bytes of hashes, and seeds */
#define KeyConfirmation_BYTES 64
#define NTRUOAEP_POLYBYTES 1053
#define NTRUOAEP_MAXPLAINTEXT 81

#define NTRUOAEP_PUBLICKEYBYTES  NTRUOAEP_POLYBYTES
#define NTRUOAEP_SECRETKEYBYTES  ((NTRUOAEP_POLYBYTES << 1) + NTRUOAEP_SYMBYTES)
#define NTRUOAEP_CIPHERTEXTBYTES  (NTRUOAEP_POLYBYTES + KeyConfirmation_BYTES)

#define NTRUOAEP_PKEM_CIPHERTEXTBYTES  (NTRUOAEP_POLYBYTES + 32)


#endif
